### ISSUE TITLE
[Suggestion] Consider using a more permissive license

### ISSUE THREAD

**Issue by RaZeR-RBI** [ezequias2d/peridot#1]
Greetings!
I'm currently faced with a need to implement 2D sprite drawing functionality in my Veldrid-based project and I've stumbled upon your
SpriteBatch implementation.

I'm looking to trying it instead of rolling my own but I'm concerned with the current license it uses.
Any chance of switching to MIT or something similar?

Thanks!

**Comment by ezequias2d** [comment]
The current license is a weak copyleft license. Is there any part of the license that prevents you from incorporating it into your project?

I don't want to change licenses for casual reasons, MPL 2.0 is less viral than other copyleft licenses, or rather, it doesn't try to force propagation of the license to more files.

The only requirements would be notification of the license and disclosure of files licensed under the same license.

What do you think?

**Comment by RaZeR-RBI** [comment]
I must admit that I'm not a lawyer and I don't have firm understanding of how weak copyleft licenses work in practice, it's exactly the reason why I'm struggling to understand in which ways I can use the code provided under such a license without hurting anybody.

Of course it's not an excuse and I should've probably did my research on it before asking, but the problem is that the amount of time required for me to fully understand how it works quite probably exceeds the time I need to implement such a library myself, that's why I've decided to just ask whether it's possible (well, that seems to be a casual reason...).

I'm familiar with the popular strong copyleft (GPL/AGPL, etc.) and permissive (MIT, BSD 2.0, etc.) licenses - they're either way 'don't use without opensourcing all the other stuff' (in case of GPL and derivatives), and 'feel free to use and transform but include the copyright notice to thank the authors' (in case of MIT and other permissive ones).

The 'weak' nature of MPL 2.0 is what concerns me - what if I decide, for example, to reuse some part of the batching code for a separate text renderer? What if I separate the common parts in a separate file, then rewrite the original ones to use that shared code?

Publishing such modified files just to comply with the license for me seems strange without including the other parts that make it work, and since they wouldn't become MPL'ed automatically, looks like I'm not legally obliged to do so, and if it's a deep part of a closed-source system, it may be hard to extract the modified parts in such a way that it becomes usable. I'm aware that lack of proper concept separation is a possible code smell, but situtations may vary, and there are always legacy code projects that are in a process for revamp.

I can't just take and integrate someone's work before making 100% sure I won't hurt anybody's IP or other things in the process. Finding out that you've misinterpreted a clause or two and unknowingly disserved the original authors is no fun for me (I tend to be a very cautious person).

I don't insist on changing it, just speaking out about my concerns why I'm not already using it in the first place. Thanks for answering!

**Comment by ezequias2d** [comment]
The license has been changed to MIT, sorry for the delay.
