### ISSUE TITLE
DrawString without Scissor stopped working

### ISSUE THREAD

**Issue by geirsagberg** [ezequias2d/peridot#3]
In `v0.2.2-alpha`, `DrawString` works as expected. However, in `v0.2.3-alpha`, nothing is drawn if no scissor is passed. This is easily reproducible in `Peridot.Demo` by not sending a scissor to the `DrawString` method.

I'm using Vulkan on MacOS, not sure if that matters?

**Comment by geirsagberg** [comment]
See this is fixed in 7eba890 :) Could you publish a new version with that?

**Comment by ezequias2d** [comment]
I already published version 0.3.0-alpha, you found a bug just before fixing it LOL

I hope the fix works for you :)
